### ISSUE TITLE
Setting bound value for multiple select.

### ISSUE THREAD

**Issue by siejones** [godbasin/vue-select2#1]
Trying to pre-select multiple values via the bound value only shows the first element in the array.

`
<Select2 :id="filterObject.domId" :options="dataOptions" :settings="select2Settings" @change="updateValue($event)" :disabled="controlsLocked" :value.sync="setValues" multiple/>

data() {
	return {
		select2Settings: {
			multiple: true
		},
		dataOptions: [{
			id: 1,
			text: 'test 1'
		},
		{
			id: 2,
			text: 'test 2'
		}],
		setValues: [1,2]
	}
},
`

**Comment by godbasin** [comment]
Fixed in version 0.2.3.
