### ISSUE TITLE
Doesn't Show Up in Component

### ISSUE THREAD

**Issue by 19peaches** [godbasin/vue-select2#10]
Hello.

For some reason the component simply doesn't show up in my component form.

I've imported it correctly:

```
import Select2 from 'v-select2-component'
```

I registered it as a component:

```
components: {
	Opener,
	Select2,		
},
```

Then use it in my form:

```
<Select2 
	class="form-control" 
	v-model="form.material" 
	:options="options" 
	:settings="{ theme: 'bootstrap' }"
	@select="selectMaterial"
</Select2>
```

Absolutely nothing shows up in the form, and using the Vue inspector tool you can see here that Select2 doesn't exist in the component:

![screen shot 2018-11-15 at 10 37 36 am](https://user-images.githubusercontent.com/1456472/48570843-8e176f00-e8c2-11e8-86d1-d212d988b148.png)

And when using the search in Vue inspector:

![screen shot 2018-11-15 at 10 37 55 am](https://user-images.githubusercontent.com/1456472/48570880-9ec7e500-e8c2-11e8-9033-dc4b67f306c5.png)

Any ideas why it would not exist at all?

Yes I'm using Vue 2, this is a production app that runs very well, I just want to swap out a different package with this one ... but it doesn't seem to work.

Thanks.

**Comment by godbasin** [comment]
1. Is there any error message output in console?
2. Does your code work correctly? For example, maybe you forget to run your dev task?

**Comment by 19peaches** [comment]
Hello @godbasin, I couldn't wait for interaction on this ticket, I replaced your component with Selectize so I could move forward with my work.
