### ISSUE TITLE
Problem to popular select

### ISSUE THREAD

**Issue by quinhone** [godbasin/vue-select2#13]
Invalid default value for prop "options": Props with type Object/Array must use a factory function to return the default value.

but the select is being populated correctly.
![return_vue](https://user-images.githubusercontent.com/3433668/49469284-eb2d8300-f7e5-11e8-91a9-fe06324c9257.JPG)

**Comment by godbasin** [comment]
Please leave more detail, as well as your code here.

**Comment by RangelReale** [comment]
Looks like newest Vue don't allow initialization of array prop as a value, it must be a function now:
https://github.com/vuejs/vue/issues/1032

```javascript
props: {
  arr: {
    type: Array,
    default: function () { return [] }
  }
}
```

**Comment by godbasin** [comment]
Version `0.3.2`  has fixed this.
