### ISSUE TITLE
Question: update selected option from js

### ISSUE THREAD

**Issue by frague59** [godbasin/vue-select2#15]
H', 
I set the selected value through a v-model field from js.
But the currently selected value is not displayed in the widget, event if it is actually in the `selected_value` field.

## Component initialization 
```html
<vue-select ref="<myRef>" v-model=selected_value" :settings"<mySettingsFunction>">
</vue-select>
```
## JS Code
```js
export default {
    ...
   data() {
       selected_value: null
    },
    methods: {
        updateSelection(selection) {
            this.selected_value = selection;
        }
    }
} 
```

**Comment by frague59** [comment]
I"ve set directly `vm.$refs["<myRef>"].value = maSelectedValue;`

**Comment by frague59** [comment]
I still have a problem with settings a multiple select:
```js
mv.selected_value.push('<my single value>");
vm.$refs["<component>"].setValue(vm.selected_value);
```
does Nothing at all...

**Comment by godbasin** [comment]
`v-model` will update the widget when your data change. It seems it was not working in your case.
Maybe you can check the demo code in [master branch](https://github.com/godbasin/vue-select2), or provide more detail about your case please. Thanks.
