### ISSUE TITLE
select2 is not a function

### ISSUE THREAD

**Issue by intellisense** [godbasin/vue-select2#19]
Hi,

I am getting the following error all over in the console:

<img width="1679" alt="Screen Shot 2019-04-23 at 12 35 45 AM" src="https://user-images.githubusercontent.com/1216537/56522715-1845bc80-6560-11e9-916e-792ba1b50854.png">

I have installed the package, and later imported it into a single component. The build is working but getting error during rendering. What could be the reason?

Thanks!

**Comment by godbasin** [comment]
Please leave more detail and code here.
Or you can  read [README](https://github.com/godbasin/vue-select2) or download the demo code in master branch first.
