### ISSUE TITLE
containerCssClass setting require full version of select2

### ISSUE THREAD

**Issue by realtebo** [godbasin/vue-select2#21]
We're trying to pass the setting [`containerCssClass` ](https://select2.org/configuration/options-api)but we got error

> Error in mounted hook: "Error: No select2/compat/containerCss"

Googling, we find that[ the option `containerCssClass` requires full version of select2](https://github.com/select2/select2/issues/3302). 

I don't know if this is the case, but I'm here to ask you how to use this option with your component.

Thanks in advance

**Comment by carlos-mora** [comment]
it seems the same is happening with dropdownCss option, the error is the same but different attr

**Comment by realtebo** [comment]
Thanks
