### ISSUE TITLE
Autofill - hidden field value not updated

### ISSUE THREAD

**Issue by bernhardberger** [godbasin/vue-select2#27]
I stumbled upon an issue with the browser's Autofill (all browsers, all platforms):

I have a select2 populated with countries. When I use the autofill feature in the browser the correct value gets displayed (for example "Germany" and the correct `<span>` with the correct value gets rendered.

However:
It doesn't update my  v-model and the hidden input remains an emtpy value. The user then has to select a different option and back to the autofill value to update the v-model.

Any ideas on how to fix/workaround this? I'm under a little pressure to get this working, so any dirty workaround would suffice for now.

**Comment by godbasin** [comment]
Maybe you can google how to delete Autofill?

**Comment by bernhardberger** [comment]
Made it work / fixed it properly. Google was my friend indeed.

**Comment by ashpuk** [comment]
@bernhardberger any chance you could elaborate on how you fixed it? I have of course been using google too but not found an answer. 
An answer here with the package on github would be useful for all :) 
thanks
