### ISSUE TITLE
selected: true is not working 

### ISSUE THREAD

**Issue by stephendeo** [godbasin/vue-select2#28]
In the options i'm setting the property 'selected: true' 

`someData: [
                { id: 1, text: 'opt1'},
                { id: 2, text: 'opt2', disabled: true },
                { id: 3, text: 'opt3', selected: true }
]`

Its not setting the selected attribute for that option

**Comment by godbasin** [comment]
#27

**Comment by godbasin** [comment]
You should use `v-model` to bind options selected.

**Comment by stephendeo** [comment]
> You should use `v-model` to bind options selected.

Sorry didn't reply before, but yes using v-model to bind the options worked perfectly. Thank you.
