### ISSUE TITLE
How to disable particular options based on certain conditions? 

### ISSUE THREAD

**Issue by ifarooq** [godbasin/vue-select2#35]
Sometimes based on certain condition we have to disable few options as we do in normal select. 
 `<option value="two" disabled="disabled">Second (disabled)</option>`
i.e
`:disabled="a==b&&x==y"`
Can we we achieve this functionality?

**Comment by godbasin** [comment]
This feature is now supported, you can try it.

**Comment by ifarooq** [comment]
Thanks much, some code samples or documentation on this? 
As currently, we pass an array of options so need some help on how to disable particular options.
