### ISSUE TITLE
ajax load options

### ISSUE THREAD

**Issue by blpraveen** [godbasin/vue-select2#36]
Using this component can I load the options via ajax.
I have posted this issue in github [link](https://stackoverflow.com/questions/66261723/vuejs-select2-search-ajax-using-laravel-framework) can you reply with example

**Comment by godbasin** [comment]
The master branch is built to showing how to use it. [You can read this](https://github.com/godbasin/vue-select2/blob/master/src/components/HelloWorld.vue).

**Comment by blpraveen** [comment]
Thanks it worked.
