### ISSUE TITLE
v-model doesn't work

### ISSUE THREAD

**Issue by Luigidefra** [godbasin/vue-select2#37]
Hi, I am using vue3-select2
v-model

Analyzing the code I saw that there is an error on line 97

`mounted() {
    this.select2 = $(this.$el)
      .find('select')
      .select2({
        placeholder: this.placeholder,
        ...this.settings,
        data: this.options
      })
      .on('select2:select select2:unselect', ev => {
        this.$emit('update:modelValue', this.select2.val());
        this.$emit('select', ev['params']['data']);
      });
    this.setValue(this.value);
  },`
  
  last row should be this.setValue(this.modelValue)

**Comment by godbasin** [comment]
Thanks. You can try `0.1.7` version.
