### ISSUE TITLE
Triggering select2 methods

### ISSUE THREAD

**Issue by pooria-h** [godbasin/vue-select2#45]
Hi there,
How can we trigger methods such as `close()`?

For example, in select2 documentation, we can do:
```
$('#mySelect2').select2('open');
```

I tried to trigger this method by reference to the component element but I had no luck, for example:

```
this.$refs.select2('close');
```

and on the component:

```
<Select2 ref="select2" />
```

**Comment by godbasin** [comment]
https://github.com/godbasin/vue-select2#events

**Comment by pooria-h** [comment]
@godbasin 

A friendly comment:

Please read more carefully. Whether it's the code or a comment. You addressed to an unrelated thing and closed the issue without asking which is rude. I asked how to trigger those methods manually.

I could find a solution anyway :)

If you can't maintain a repo you can always ask for help orbsome contribution.

Take care

**Comment by godbasin** [comment]
> @godbasin
> 
> A friendly comment:
> 
> Please read more carefully. Whether it's the code or a comment. You addressed to an unrelated thing and closed the issue without asking which is rude. I asked how to trigger those methods manually.
> 
> I could find a solution anyway :)
> 
> If you can't maintain a repo you can always ask for help or some contribution.
> 
> Take care

Sorry I thought it was an issue asking how to listen to `close` event so I refer it to ducuments and close it.
If you want to trigger it, you can give the component an id:
```
<Select2 id="mySelect2" />
```
Then trigger it as select2 documentation as you said:
```
$('#mySelect2').select2('open');
```

And friendly comment too:
It's my fault that not read this issue carefully. I apologize for that.
But you can reopen it or call attention to me again, that's the function of an issue.

Take care too.

**Comment by pooria-h** [comment]
@godbasin 
Thanks for the response.

Your solution may work only if you use JQuery in your project.
I share my solution for those who don't use JQuery.

```
<Select2
        @open.once="onOpenOnce"
        @open="onOpen"
        @change="setValue"
        :value="clonedValue"
        :id="id"
        :options="options"
        :settings="{ multiple: true, closeOnSelect: false }" />
```

```
// I have a custom button in the dropdown whose job is selecting all of the items
// The issue is select2 doesn't update its DOM if you update the model by passing `value` or `v-model`, so you have to close the dropdown manually to force the DOM update
selectAll () {
      // here is not related to the issue, I'm just setting the value
      this.clonedValue = [];
      this.options.forEach(value => this.clonedValue.push(value.id.toString()));
      this.$emit('change', this.clonedValue);

      // Here I make the dropdown hidden by setting CSS
      document.getElementsByClassName('select2-dropdown')[0].style.display = 'none';
      document.getElementsByClassName('select2-container')[0].classList.remove('select2-container--open');
    },
```

```
onOpen () {
      setTimeout(() => {
        // Here I make the dropdown visible again
        document.getElementsByClassName('select2-dropdown')[0].style.display = 'block';
      }, 100);
    }
```

```
onOpenOnce () {
  // Here I append some elements to the dropdown which is not related to the issue
}
```

It may not be a clean solution. If we could access Select2 methods through the component like this `this.$refs.select2('close');` it could be a cleaner but it seems it's not possible.

[Imgur](https://imgur.com/stxrvAQ)


Stay safe
