### ISSUE TITLE
Event DOM not working

### ISSUE THREAD

**Issue by masan27** [godbasin/vue-select2#46]
Hi @godbasin.
I am using vue3-select2, Is working But when i try event onchange or oninput or etc, i get message warning
"Component emitted event "select" but it is neither declared in the emits option nor as an "onSelect" prop."

whats wrong? Can you help me? Thanks...

Edit:

When try onselect It's working, sorry my fault.

**Comment by masan27** [comment]
> Hi @godbasin.
> I am using vue3-select2, Is working But when i try event onchange or oninput or etc, i get message warning
> "Component emitted event "select" but it is neither declared in the emits option nor as an "onSelect" prop."
> 
> whats wrong? Can you help me? Thanks...

**Comment by 28itShaviSilva** [comment]
@masan27 how did you able to fix this issue ? I'm still struggling to fix same issue

**Comment by masan27** [comment]
> @masan27 how did you able to fix this issue ? I'm still struggling to fix same issue

just change event onchange to onselect

**Comment by CarlosIvanHuerta** [comment]
> Hi @godbasin. I am using vue3-select2, Is working But when i try event onchange or oninput or etc, i get message warning "Component emitted event "select" but it is neither declared in the emits option nor as an "onSelect" prop."
> 
> whats wrong? Can you help me? Thanks...
> 
> Edit:
> 
> When try onselect It's working, sorry my fault.

Hello.. MY SOLUTION
EDIT FILE /node_modules/vue3-select2-component/src/Select2.vue
Line 19 :)
` emits: ['update:modelValue','select'],`

**Comment by neverender24** [comment]
@CarlosIvanHuerta any way to embed the solution in the app?
